/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-07-18 09:15:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/ksm/jsp4/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web06/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/board/../inc/footer.jsp", Long.valueOf(1657691394293L));
    _jspx_dependants.put("/WEB-INF/views/board/../inc/header.jsp", Long.valueOf(1657696999851L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1655111722494L));
    _jspx_dependants.put("jar:file:/D:/ksm/jsp4/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web06/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>서브페이지</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"scont\">\r\n");
      out.write("<header id=\"header\" class=\"header\">\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"icon\" href=\"../../img_total/n_favicon_n_16.png\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"https://kostat.go.kr/img_total/favicon_kostat.ico\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/NotoSansKR-Hestia_Main.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style_content.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style_layout_master.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/master.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style_board.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/reset_new_n.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/code.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<title> header </title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("        <div id=\"skip\">\r\n");
      out.write("            <p class=\"Hidden\">반복영역 건너뛰기</p>\r\n");
      out.write("           <ul class=\"accessibility\">\r\n");
      out.write("               	<li><a href=\"#mcont_s\">본문바로가기</a></li>\r\n");
      out.write("               	<li><a href=\"#gnb_s1\">주요메뉴바로가기</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("       </div>\r\n");
      out.write("        <div id=\"header_n\">             \r\n");
      out.write("            <div id=\"tnb_layout\" style=\"background-color: #4e4e4e;\">\r\n");
      out.write("            <div class=\"t_nav\">\r\n");
      out.write("                <h1 class=\"t_logo\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/logo2.png\" style=\"height: auto; width: 120px\" alt=\"통계청\" /></a></h1>\r\n");
      out.write("                <ul class=\"sitelink_r\">\r\n");
      out.write("                \r\n");
      out.write("	                ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	                \r\n");
      out.write("	                ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	                \r\n");
      out.write("	                ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	                \r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>  \r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"mnb_layout\">\r\n");
      out.write("            \r\n");
      out.write("            <!-- 통계청 검색기능 -->\r\n");
      out.write("            <h2 class=\"Hidden\">통합검색</h2>\r\n");
      out.write("    <div class=\"search_m_open\">\r\n");
      out.write("       <a href=\"http://kostat.go.kr/wnsearch/search.jsp\" target=\"_blank\">검색 열기</a>\r\n");
      out.write("      </div>\r\n");
      out.write("            <div id=\"search\"> \r\n");
      out.write("            <script> \r\n");
      out.write("    function quickSearch(query){\r\n");
      out.write("        var frm = document.sForm;\r\n");
      out.write("        frm.action = \"https://kostat.go.kr/wnsearch/search.jsp\";\r\n");
      out.write("        frm.query.value = query;\r\n");
      out.write("        frm.submit();\r\n");
      out.write("    }\r\n");
      out.write("        function goSearch(){\r\n");
      out.write("            var frm = document.sForm;\r\n");
      out.write("            var name = document.getElementById(\"query\").value;\r\n");
      out.write("    if(name  == null || name == \"\"){\r\n");
      out.write("    alert(\"검색어를 입력하세요.\");\r\n");
      out.write("    document.getElementById(\"query\").focus();\r\n");
      out.write("    return false;\r\n");
      out.write("    }\r\n");
      out.write("                frm.action = \"https://kostat.go.kr/wnsearch/search.jsp\";\r\n");
      out.write("                frm.submit();\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        function handlepress(){	\r\n");
      out.write("            if(event.keyCode == 13){	\r\n");
      out.write("                goSearch();	\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        function selectWord(word){\r\n");
      out.write("            var frm = document.sForm;\r\n");
      out.write("            frm.query.value=word;\r\n");
      out.write("            frm.submit();\r\n");
      out.write("        }\r\n");
      out.write("        function kostat() {\r\n");
      out.write("            alert(\"현재 검색이 원활히 되지 않고 있습니다. 이용에 불편을 드려 죄송합니다. 빠른 시일내에 복구하도록 하겠습니다.\");\r\n");
      out.write("        }\r\n");
      out.write("    </script><noscript>스크립트 기능이 중지되어 있어, 게시판 화면을 정상적으로 표시할 수 없습니다. </noscript>\r\n");
      out.write("    <form name=\"sForm\" method=\"post\" action=\"https://kostat.go.kr/wnsearch/search.jsp\" onsubmit=\"return goSearch();\">\r\n");
      out.write("          <fieldset>\r\n");
      out.write("          <legend class=\"Hidden\">통합검색</legend>\r\n");
      out.write("        <label for=\"collection\" class=\"Hidden\">검색분류</label>\r\n");
      out.write("        <select name=\"collection\" id=\"collection\"  title=\"검색분류\">\r\n");
      out.write("    <option value=\"ALL\" selected=\"selected\">통합검색</option>\r\n");
      out.write("            <option value=\"web_bodo\">통계청 누리집</option>\r\n");
      out.write("            <option value=\"statDB\">국가통계포털(KOSIS) 통계표</option>\r\n");
      out.write("            <option value=\"enara\" >한눈에알아보는나라지표(e-나라지표)</option>\r\n");
      out.write("            <option value=\"class\" >통계분류</option>\r\n");
      out.write("            <option value=\"online\" >온라인간행물</option>\r\n");
      out.write("            <option value=\"metaDB\" >통계설명자료</option>\r\n");
      out.write("            <option value=\"statTerms\">통계용어</option>\r\n");
      out.write("            <option value=\"employee\">직원검색</option>\r\n");
      out.write("            <option value=\"hire\">채용정보</option>\r\n");
      out.write("        </select>\r\n");
      out.write("            <label for=\"query\"  class=\"Hidden\" >통합검색창</label>\r\n");
      out.write("            <input name=\"query\" type=\"text\" id=\"query\" class=\"searchInput\" value=\"\" title=\"검색어\" style=\"ime-mode:active;\" />\r\n");
      out.write("            <label for=\"btn_ts_search\"  class=\"Hidden\">검색</label>\r\n");
      out.write("    <input type=\"submit\" id=\"btn_ts_search\"  value=\"검색\"/>\r\n");
      out.write("          </fieldset>\r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"relation_link\">\r\n");
      out.write("                <li class=\"fst\"><a href=\"http://kostat.go.kr/\"  target=\"_blank\" title=\"새창\" class=\"c_point\"><strong>민원</strong></a></li>\r\n");
      out.write("                <li><a href=\"http://kostat.go.kr/\" target=\"_blank\" title=\"새창\">통계이해</a></li>\r\n");
      out.write("                <li><a href=\"http://kostat.go.kr/\"  target=\"_blank\" title=\"새창\">채용</a></li>\r\n");
      out.write("                <li class=\"last\"><a href=\"http://kostat.go.kr/\"  target=\"_blank\" title=\"새창\">통계조사</a></li>\r\n");
      out.write("             </ul>   \r\n");
      out.write("              </div>\r\n");
      out.write("              </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("    <div id=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <div id=\"slnb\">\r\n");
      out.write("    <h2 class=\"title\">자바(JAVA)</h2>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li id=\"\"><a href=\"\" class=\"M_on\">JAVA</a>\r\n");
      out.write("                <ul class=\"mn_depth2\">\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list.do\" class=\"M_on\">자바의 개요</a></li>	<!-- 다음페이지만들때 여기서 M_ON바꿔줘야함 -->\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list2.do\">특징</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list3.do\">문법</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list4.do\">JAVA Script</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list5.do\">JDK</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write(" \r\n");
      out.write("    <div id=\"contgr\">\r\n");
      out.write("        <div id=\"path\" class=\"sub_nav\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"home\" id=\"path_h\"><span class=\"Hidden\">home</span></a>\r\n");
      out.write("            <a href=\"\">자바(JAVA)</a>\r\n");
      out.write("            <a href=\"\">JAVA</a>\r\n");
      out.write("            <span class=\"bold last\">자바의개요</span>\r\n");
      out.write("        </div> \r\n");
      out.write("            \r\n");
      out.write("            <ul class=\"cont_t_icon\">\r\n");
      out.write("                <li><a title=\"주소복사\" href=\"\" class=\"link_icon\"><span class=\"Hidden\">주소복사</span></a></li>\r\n");
      out.write("                <li><a title=\"인쇄하기\" href=\"\" class=\"line_none print_icon\" ><!-- a title=\"새창\" href=\"//kostat.go.kr\" onclick=\"window.print(); return false;\" class=\"line_none print_icon\" --><span class=\"Hidden\">프린트</span></a></li>        \r\n");
      out.write("            </ul>\r\n");
      out.write("            <h1 class=\"h1_tit\">자바란?</h1>\r\n");
      out.write("    <div class=\"contents\" id=\"conts\">\r\n");
      out.write("        <div id=\"ct_text\">\r\n");
      out.write("            <div class=\"cont_tbox\">\r\n");
      out.write("                <p class=\"ctb_icon0101\">\r\n");
      out.write("               C#과 문법적 성향이 굉장히 비슷하며, 그에 비해 2019년 Q3에서 가장 많이 이용하는 언어로 뽑혔다.\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("             <!-- 스킨에 따른 아티클 리스트 스타일-->\r\n");
      out.write("<!--             <div id=\"tabDiv\" class=\"tab_type02\">\r\n");
      out.write("                <ul id=\"tabUl\" class=\"tab_list02\">\r\n");
      out.write("                    <li class=\"t_on\"><a href=\"/portal/korea/kor_ip/9/1/1/index.action\">주요내용</a></li>\r\n");
      out.write("                    <li><a href=\"/portal/korea/kor_ip/9/1/2/index.action\">청구절차</a></li>\r\n");
      out.write("                    <li><a href=\"/portal/korea/kor_ip/9/1/3/index.action\">불복구제절차 및 방법</a></li>\r\n");
      out.write("                    <li><a href=\"/portal/korea/kor_ip/9/1/4/index.action\">수수료</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div> -->\r\n");
      out.write("            \r\n");
      out.write("        <h2 class=\"h2_tit\">주요내용</h2><h3 class=\"h3_tit mt25\">분류</h3>\r\n");
      out.write("            <div class=\"claimant_box\">\r\n");
      out.write("                <dl>\r\n");
      out.write("                    <dt class=\"cl_icon01\">Java SE </dt>\r\n");
      out.write("                    <dd>\r\n");
      out.write("                        <span>대부분의 사람들이 가장 많이 접하는 표준 에디션. Java의 핵심 API와 기능들을 제공한다. JDK 항목도 참고. </span>\r\n");
      out.write("                    </dd>\r\n");
      out.write("                </dl>\r\n");
      out.write("                <dl>\r\n");
      out.write("                    <dt class=\"cl_icon02\">Jakarta EE, 구 Java EE </dt>\r\n");
      out.write("                    <dd>\r\n");
      out.write("                        <span>기업에서 운영하는 서버 페이지에 특화된 에디션이다. JSP와 서블릿을 비롯한 웹 애플리케이션 서버에 관련된 기술들이 포함되어 있다.</span>\r\n");
      out.write("                    </dd>\r\n");
      out.write("                </dl>\r\n");
      out.write("                <dl>\r\n");
      out.write("                    <dt class=\"cl_icon03\">Java ME </dt>\r\n");
      out.write("                    <dd>\r\n");
      out.write("                        <span>피처폰, PDA, 셋톱박스, 센서 등의 임베디드 시스템 환경에 특화된 경량 에디션이다. </span>\r\n");
      out.write("                    </dd>\r\n");
      out.write("                </dl>\r\n");
      out.write("            </div>\r\n");
      out.write("        <h3 class=\"h3_tit\">코드 방식</h3>\r\n");
      out.write("            <p>class Main {\r\n");
      out.write("    public static void main(String[] args) {\r\n");
      out.write("        System.out.println(\"Hello, world!\");\r\n");
      out.write("    }\r\n");
      out.write("}			</p>\r\n");
      out.write("        <h3 class=\"h3_tit\">개요</h3>\r\n");
      out.write("            <p>\r\n");
      out.write("            썬 마이크로시스템즈에서 1995년에 개발한 객체 지향 프로그래밍 언어. 창시자는 제임스 고슬링이다. \r\n");
      out.write("            2010년에 오라클이 썬 마이크로시스템즈를 인수하면서 Java의 저작권을 소유하였다. 현재는 OpenJDK는 GPL2이나 오라클이 배포하는\r\n");
      out.write("             Oracle JDK는 상업라이선스로 2019년 1월부터 유료화정책을 강화하고 있다. Java EE는 이클립스 재단의 소유이다. \r\n");
      out.write("             Java 언어는 J2SE 1.4부터는 Java Community Process (JCP)에서 개발을 주도하고 있다.\r\n");
      out.write("            </p>\r\n");
      out.write("        <h3 class=\"h3_tit\">운영 및 개발</h3>\r\n");
      out.write("    <table class=\"tb_type1\">\r\n");
      out.write("        <caption>정보공개 책임관 및 담당자 관한 구분, 소속, 직위, 전화번호 정보를 제공하고 있습니다.</caption>\r\n");
      out.write("        <colgroup>\r\n");
      out.write("            <col style=\"WIDTH: 30%\">\r\n");
      out.write("            <col style=\"WIDTH: 30%\">\r\n");
      out.write("            <col style=\"WIDTH: 15%\">\r\n");
      out.write("            <col style=\"WIDTH: 25%\">\r\n");
      out.write("        </colgroup>\r\n");
      out.write("        <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th scope=\"col\">개발</th>\r\n");
      out.write("                <th scope=\"col\">개발자</th>\r\n");
      out.write("                <th scope=\"col\">최초버전</th>\r\n");
      out.write("                <th scope=\"col\">링크</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("    <tbody>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td>오라클</td>\r\n");
      out.write("        <td>제임스 고슬링</td>\r\n");
      out.write("        <td>1.0 (1995.01.23)</td>\r\n");
      out.write("        <td><a href=\"https://www.oracle.com/java/\">https://www.oracle.com/java/</a></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("\r\n");
      out.write("    </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("     </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <footer id=\"footer\" class=\"footer\">\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title> footer </title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"footer_n\">\r\n");
      out.write("        <div class=\"fnb_bg\">\r\n");
      out.write("                    <div class=\"fnb_group\">\r\n");
      out.write("                        <ul class=\"fg_list\">\r\n");
      out.write("                            <li class=\"fst\"><a href=\"\">이용안내</a></li>                \r\n");
      out.write("                            <li><a href=\"\"><span class=\"c_blue\">개인정보처리방침</span></a></li>\r\n");
      out.write("                            <li><a href=\"\">저작권정책</a></li>                  \r\n");
      out.write("                            <li><a href=\"\">누리집개선의견</a></li>\r\n");
      out.write("                            <li class=\"last\"><a href=\"\">찾아오시는길</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div id=\"siteListBox\">\r\n");
      out.write("                            <div id=\"siteList01\" class=\"siteList\">\r\n");
      out.write("                                <a href=\"http://kostat.go.kr/regional/gi/index.action\" onclick=\"kostatServiceDis('kostatagency','open');return false;\">소속기관</a>\r\n");
      out.write("                                <div class=\"moreSiteHidden\" id=\"kostatagency\">\r\n");
      out.write("                                    <ul class=\"sitetype01 bulType01\">\r\n");
      out.write("                                        <li><a href=\"\" target=\"_blank\" title=\"새 창으로 이동\">통계교육원</a></li>\r\n");
      out.write("                                        <li><a href=\"\" target=\"_blank\" title=\"새 창으로 이동\">통계개발원</a></li>\r\n");
      out.write("                                        <li> <a href=\"\"  target=\"_blank\" title=\"새 창으로 이동\">경인지방통계청</a> </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <p>소속기관<a href=\"index.html\" onclick=\"kostatServiceDis('kostatagency','close');return false;\">닫기</a></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div id=\"siteList02\" class=\"siteList\">\r\n");
      out.write("                                <a href=\"\" onclick=\"kostatServiceDis('kostatinfo','open');return false;\">통계정보</a>\r\n");
      out.write("                                <div class=\"moreSiteHidden\" id=\"kostatinfo\">\r\n");
      out.write("                                    <div class=\"siteType02\">\r\n");
      out.write("                                        <dl class=\"site_g\">\r\n");
      out.write("                                            <dt>통계정보</dt>\r\n");
      out.write("                                            <dd>\r\n");
      out.write("                                                <ul class=\"bulType01\">\r\n");
      out.write("                                                    <li><a href=\"\" target=\"_blank\"> 국가통계포털(KOSIS)</a></li>\r\n");
      out.write("                                                    <li><a href=\"\" target=\"_blank\">통계지리정보서비스(SGIS)</a></li>\r\n");
      out.write("                                                    <li><a href=\"\" target=\"_blank\">국가지표체계</a> </li>\r\n");
      out.write("                                                    <li><a href=\"\" target=\"_blank\">한눈에알아보는나라지표(e-나라지표)</a> </li>              \r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </dd>\r\n");
      out.write("                                        </dl>\r\n");
      out.write("                                        <dl class=\"site_g\">\r\n");
      out.write("                                            <dt>통계정책</dt>\r\n");
      out.write("                                            <dd>\r\n");
      out.write("                                                <ul class=\"bulType01\">\r\n");
      out.write("                                                    <li> <a href=\"\" target=\"_blank\" title=\"새 창으로 이동\" onclick=\"dummyAndPop2('http://narastat.kr/pms/index.do','/dummyURL?bmode=jongBo10');return false;\">통계정책관리시스템</a> </li>\r\n");
      out.write("                                                    <li> <a href=\"\" target=\"_blank\" title=\"새 창으로 이동\" onclick=\"dummyAndPop3('kostat.go.kr/policy/ssm/index.action','/dummyURL?bmode=jongBo11');return false;\">국가통계대행</a> </li>\r\n");
      out.write("                                                    <li><a href=\"\" target=\"_blank\" title=\"새 창으로 이동\" onclick=\"dummyAndPop2('http://kosis.kr/publication/publicationThema.do','/dummyURL?bmode=jongBo12');return false;\">온라인간행물</a></li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </dd>\r\n");
      out.write("                                        </dl>\r\n");
      out.write("                                        <dl class=\"site_g\">\r\n");
      out.write("                                            <dt>통계조사</dt>\r\n");
      out.write("                                            <dd>\r\n");
      out.write("                                                <ul class=\"bulType01\">\r\n");
      out.write("                                                    <li><a href=\"\"  target=\"_blank\">인구주택총조사</a> </li>\r\n");
      out.write("                                                    <li><a href=\"\" target=\"_blank\">농림어업총조사</a> </li>\r\n");
      out.write("                                                    <li><a href=\"\" target=\"_blank\">경제총조사 </a> </li>                                                                             \r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </dd>\r\n");
      out.write("                                        </dl>\r\n");
      out.write("                                        <dl class=\"site_g\">\r\n");
      out.write("                                            <dt>관련누리집</dt>\r\n");
      out.write("                                            <dd>\r\n");
      out.write("                                                <ul class=\"bulType01\">\r\n");
      out.write("                                                    <li> <a href=\"\" target=\"_blank\">소비자물가지수</a> </li>\r\n");
      out.write("                                                    <li> <a href=\"\"  target=\"_blank\">소득</a> </li>\r\n");
      out.write("                                                    <li> <a href=\"\" target=\"_blank\">100대 지표</a> </li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </dd>\r\n");
      out.write("                                        </dl>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p>통계정보 누리집<a href=\"index.html\" onclick=\"kostatServiceDis('kostatinfo','close');return false;\">닫기</a></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"add_group\">\r\n");
      out.write("                    <address>[1004] 일산동구 고양대로 956(식사동, 어딘가) 팩스 000-111-1004 / <strong>\r\n");
      out.write("                    <span class=\"call\">통계청콜센터 02-1004-1004</span> / <span class=\"call\">국번없이 110</span>\r\n");
      out.write("        </strong></address>\r\n");
      out.write("                    <p class=\"copy\">ⓒ Statistics Korea. All rights reserved since 2022.</p>\r\n");
      out.write("                    <h2 class=\"Hidden\">소셜미디어</h2>\r\n");
      out.write("                    <ul class=\"sns_list\">\r\n");
      out.write("                        <li class=\"icon_y\"><a href=\"http://kostat.go.kr/\" target=\"_blank\" onclick=\"dummyAndPop2('https://www.youtube.com/');return false;\"><span class=\"txt_sm\">유튜브</span></a></li>\r\n");
      out.write("                        <li class=\"icon_f\"><a href=\"http://kostat.go.kr/\" target=\"_blank\" onclick=\"dummyAndPop2('http://www.facebook.com/');return false;\"><span class=\"txt_sm\">페이스북</span></a></li>\r\n");
      out.write("                        <li class=\"icon_t\"><a href=\"http://kostat.go.kr/\" target=\"_blank\" onclick=\"dummyAndPop2('https://twitter.com/');return false;\"><span class=\"txt_sm\">트위터</span></a></li>\r\n");
      out.write("                        <li class=\"icon_b\"><a href=\"http://kostat.go.kr/\" target=\"_blank\" onclick=\"dummyAndPop2('https://blog.naver.com/');return false;\"><span class=\"txt_sm\">블로그</span></a></li>\r\n");
      out.write("                        <li class=\"icon_k\"><a href=\"http://kostat.go.kr/\"  target=\"_blank\" onclick=\"dummyAndPop2('https://www.instagram.com/');return false;\"><span class=\"txt_sm\">인스타그램</span></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- 소셜비디어 E -->\r\n");
      out.write("                    <p class=\"f_img02\"><a href=\"http://kostat.go.kr/file_total/WAQC_210910_kostat.pdf\" target=\"_blank\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/img_main/ico_wa.jpg\" alt=\"과학기술정보통신부 WEB ACCESSIBILITY 마크(웹 접근성 품질인증 마크)\" /></a></p>\r\n");
      out.write("                    <p class=\"f_img01\"><a href=\"http://www.kogl.or.kr/index.do\" target=\"_blank\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/img_main/kogl.gif\" alt=\"OPEN 공공누리:공공저작물 새창으로 열기\" /></a></p>\r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("    // 푸터에 소속기관 셀렉터창\r\n");
      out.write("function kostatServiceDis(id,evnt){                                                                                                                                 \r\n");
      out.write("	var clazz = document.getElementById(id).className;                                                                                                                \r\n");
      out.write("	if(evnt == \"open\"){                                                                                                                                               \r\n");
      out.write("  	if(clazz == \"moreSite\"){\r\n");
      out.write("  		document.getElementById(id).className = \"moreSiteHidden\";                                                                                                 \r\n");
      out.write("  	}else{                                                                                                                                                          \r\n");
      out.write("  		document.getElementById(id).className = \"moreSite\";                                                                                                        \r\n");
      out.write("  	}	                                                                                                                                                              \r\n");
      out.write("	}else{                                                                                                                                                            \r\n");
      out.write("		document.getElementById(id).className = \"moreSiteHidden\";                                                                                                   \r\n");
      out.write("	}                                                                                                                                                                 \r\n");
      out.write("}\r\n");
      out.write("function quickServiceDis(id,evnt){\r\n");
      out.write("	var clazz = document.getElementById(id);\r\n");
      out.write("	var clazzMain = document.getElementById(id+\"_main\");\r\n");
      out.write("	if(evnt == \"open\"){\r\n");
      out.write("  		clazz.className = \"\";\r\n");
      out.write("  		clazzMain.className = \"Dis_none\";\r\n");
      out.write("	}else{\r\n");
      out.write("  		clazz.className = \"Dis_none\";\r\n");
      out.write("  		clazzMain.className = \"\";\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/common.js\" ></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-3.3.1.min.js\" ></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/menuNew.js\" ></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/rollingIndexBanner.js\" ></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/mainBodo.js\" ></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/new_main.js\" ></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/board/boardList.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path1");
      // /WEB-INF/views/board/boardList.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/boardList.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/board/../inc/header.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("path1");
      // /WEB-INF/views/board/../inc/header.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/../inc/header.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/board/../inc/header.jsp(35,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty sid}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	                    <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/loginForm.do\" >로그인</a></li>\r\n");
          out.write("	                    <li class=\"eng\"><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/joinForm.do\">회원가입</a></li>\r\n");
          out.write("	                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/board/../inc/header.jsp(40,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sid=='admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	                    <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/list.do\" >회원목록</a></li>\r\n");
          out.write("	                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/board/../inc/header.jsp(44,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty sid}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	                    <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/read.do\" >마이페이지</a></li>\r\n");
          out.write("	                    <li class=\"eng\"><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/logout.do\">로그아웃</a></li>\r\n");
          out.write("	                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/views/board/../inc/footer.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("path1");
      // /WEB-INF/views/board/../inc/footer.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/../inc/footer.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }
}
