/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-07-18 08:15:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardList4_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/ksm/jsp4/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web06/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/board/../inc/footer.jsp", Long.valueOf(1657691394293L));
    _jspx_dependants.put("/WEB-INF/views/board/../inc/header.jsp", Long.valueOf(1657696999851L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1655111722494L));
    _jspx_dependants.put("jar:file:/D:/ksm/jsp4/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web06/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link href=\"../css/code.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<title>서브페이지</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"scont\">\r\n");
      out.write("<header id=\"header\" class=\"header\">\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"icon\" href=\"../../img_total/n_favicon_n_16.png\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"https://kostat.go.kr/img_total/favicon_kostat.ico\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/NotoSansKR-Hestia_Main.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style_content.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style_layout_master.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/master.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style_board.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/reset_new_n.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/code.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<title> header </title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("        <div id=\"skip\">\r\n");
      out.write("            <p class=\"Hidden\">반복영역 건너뛰기</p>\r\n");
      out.write("           <ul class=\"accessibility\">\r\n");
      out.write("               	<li><a href=\"#mcont_s\">본문바로가기</a></li>\r\n");
      out.write("               	<li><a href=\"#gnb_s1\">주요메뉴바로가기</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("       </div>\r\n");
      out.write("        <div id=\"header_n\">             \r\n");
      out.write("            <div id=\"tnb_layout\" style=\"background-color: #4e4e4e;\">\r\n");
      out.write("            <div class=\"t_nav\">\r\n");
      out.write("                <h1 class=\"t_logo\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/logo2.png\" style=\"height: auto; width: 120px\" alt=\"통계청\" /></a></h1>\r\n");
      out.write("                <ul class=\"sitelink_r\">\r\n");
      out.write("                \r\n");
      out.write("	                ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	                \r\n");
      out.write("	                ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	                \r\n");
      out.write("	                ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	                \r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>  \r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"mnb_layout\">\r\n");
      out.write("            \r\n");
      out.write("            <!-- 통계청 검색기능 -->\r\n");
      out.write("            <h2 class=\"Hidden\">통합검색</h2>\r\n");
      out.write("    <div class=\"search_m_open\">\r\n");
      out.write("       <a href=\"http://kostat.go.kr/wnsearch/search.jsp\" target=\"_blank\">검색 열기</a>\r\n");
      out.write("      </div>\r\n");
      out.write("            <div id=\"search\"> \r\n");
      out.write("            <script> \r\n");
      out.write("    function quickSearch(query){\r\n");
      out.write("        var frm = document.sForm;\r\n");
      out.write("        frm.action = \"https://kostat.go.kr/wnsearch/search.jsp\";\r\n");
      out.write("        frm.query.value = query;\r\n");
      out.write("        frm.submit();\r\n");
      out.write("    }\r\n");
      out.write("        function goSearch(){\r\n");
      out.write("            var frm = document.sForm;\r\n");
      out.write("            var name = document.getElementById(\"query\").value;\r\n");
      out.write("    if(name  == null || name == \"\"){\r\n");
      out.write("    alert(\"검색어를 입력하세요.\");\r\n");
      out.write("    document.getElementById(\"query\").focus();\r\n");
      out.write("    return false;\r\n");
      out.write("    }\r\n");
      out.write("                frm.action = \"https://kostat.go.kr/wnsearch/search.jsp\";\r\n");
      out.write("                frm.submit();\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        function handlepress(){	\r\n");
      out.write("            if(event.keyCode == 13){	\r\n");
      out.write("                goSearch();	\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        function selectWord(word){\r\n");
      out.write("            var frm = document.sForm;\r\n");
      out.write("            frm.query.value=word;\r\n");
      out.write("            frm.submit();\r\n");
      out.write("        }\r\n");
      out.write("        function kostat() {\r\n");
      out.write("            alert(\"현재 검색이 원활히 되지 않고 있습니다. 이용에 불편을 드려 죄송합니다. 빠른 시일내에 복구하도록 하겠습니다.\");\r\n");
      out.write("        }\r\n");
      out.write("    </script><noscript>스크립트 기능이 중지되어 있어, 게시판 화면을 정상적으로 표시할 수 없습니다. </noscript>\r\n");
      out.write("    <form name=\"sForm\" method=\"post\" action=\"https://kostat.go.kr/wnsearch/search.jsp\" onsubmit=\"return goSearch();\">\r\n");
      out.write("          <fieldset>\r\n");
      out.write("          <legend class=\"Hidden\">통합검색</legend>\r\n");
      out.write("        <label for=\"collection\" class=\"Hidden\">검색분류</label>\r\n");
      out.write("        <select name=\"collection\" id=\"collection\"  title=\"검색분류\">\r\n");
      out.write("    <option value=\"ALL\" selected=\"selected\">통합검색</option>\r\n");
      out.write("            <option value=\"web_bodo\">통계청 누리집</option>\r\n");
      out.write("            <option value=\"statDB\">국가통계포털(KOSIS) 통계표</option>\r\n");
      out.write("            <option value=\"enara\" >한눈에알아보는나라지표(e-나라지표)</option>\r\n");
      out.write("            <option value=\"class\" >통계분류</option>\r\n");
      out.write("            <option value=\"online\" >온라인간행물</option>\r\n");
      out.write("            <option value=\"metaDB\" >통계설명자료</option>\r\n");
      out.write("            <option value=\"statTerms\">통계용어</option>\r\n");
      out.write("            <option value=\"employee\">직원검색</option>\r\n");
      out.write("            <option value=\"hire\">채용정보</option>\r\n");
      out.write("        </select>\r\n");
      out.write("            <label for=\"query\"  class=\"Hidden\" >통합검색창</label>\r\n");
      out.write("            <input name=\"query\" type=\"text\" id=\"query\" class=\"searchInput\" value=\"\" title=\"검색어\" style=\"ime-mode:active;\" />\r\n");
      out.write("            <label for=\"btn_ts_search\"  class=\"Hidden\">검색</label>\r\n");
      out.write("    <input type=\"submit\" id=\"btn_ts_search\"  value=\"검색\"/>\r\n");
      out.write("          </fieldset>\r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"relation_link\">\r\n");
      out.write("                <li class=\"fst\"><a href=\"http://kostat.go.kr/\"  target=\"_blank\" title=\"새창\" class=\"c_point\"><strong>민원</strong></a></li>\r\n");
      out.write("                <li><a href=\"http://kostat.go.kr/\" target=\"_blank\" title=\"새창\">통계이해</a></li>\r\n");
      out.write("                <li><a href=\"http://kostat.go.kr/\"  target=\"_blank\" title=\"새창\">채용</a></li>\r\n");
      out.write("                <li class=\"last\"><a href=\"http://kostat.go.kr/\"  target=\"_blank\" title=\"새창\">통계조사</a></li>\r\n");
      out.write("             </ul>   \r\n");
      out.write("              </div>\r\n");
      out.write("              </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("    <div id=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <div id=\"slnb\">\r\n");
      out.write("    <h2 class=\"title\">자바(JAVA)</h2>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li id=\"\"><a href=\"\" class=\"M_on\">JAVA</a>\r\n");
      out.write("                <ul class=\"mn_depth2\">\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list.do\">자바의 개요</a></li>	<!-- 다음페이지만들때 여기서 M_ON바꿔줘야함 -->\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list2.do\">특징</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list3.do\">문법</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list4.do\" class=\"M_on\">JAVA Script</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list5.do\">JDK</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write(" \r\n");
      out.write("    <div id=\"contgr\">\r\n");
      out.write("        <div id=\"path\" class=\"sub_nav\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"home\" id=\"path_h\"><span class=\"Hidden\">home</span></a>\r\n");
      out.write("            <a href=\"\">자바(JAVA)</a>\r\n");
      out.write("            <span class=\"bold last\">JAVA Script</span>\r\n");
      out.write("        </div> \r\n");
      out.write("            \r\n");
      out.write("            <ul class=\"cont_t_icon\">\r\n");
      out.write("                <li><a title=\"주소복사\" href=\"\" class=\"link_icon\"><span class=\"Hidden\">주소복사</span></a></li>\r\n");
      out.write("                <li><a title=\"인쇄하기\" href=\"\" class=\"line_none print_icon\" ><!-- a title=\"새창\" href=\"//kostat.go.kr\" onclick=\"window.print(); return false;\" class=\"line_none print_icon\" --><span class=\"Hidden\">프린트</span></a></li>        \r\n");
      out.write("            </ul>\r\n");
      out.write("            <h1 class=\"h1_tit\">JS(JavaScript)</h1>\r\n");
      out.write("            \r\n");
      out.write("   <h3 class=\"h3_tit\">개요</h3>\r\n");
      out.write("   <ul class=\"list_style01\">\r\n");
      out.write("	<li><span class=\"bold\">\r\n");
      out.write("	document.write(\"Hello, world!\"); // HTML 문서에 출력된다.<br>\r\n");
      out.write("	alert(\"Hello, world!\"); // 알림창으로 출력된다.<br>\r\n");
      out.write("	console.log(\"Hello, world!\"); // 보통 F12를 누르면 보이는 콘솔 창에 출력된다.</span>\r\n");
      out.write("		<p>\r\n");
      out.write("		Ecma International의 프로토타입 기반의 프로그래밍 언어로, 스크립트 언어에 해당된다.<br> \r\n");
      out.write("		특수한 목적이 아닌 이상 모든 웹 브라우저에 인터프리터가 내장되어 있다. 오늘날 HTML, CSS와 함께 웹을 구성하는 요소 중 하나다.<br>\r\n");
      out.write("		HTML이 웹 페이지의 기본 구조를 담당하고, CSS가 디자인을 담당한다면 JavaScript는 <br>클라이언트 단에서 웹 페이지가 동작하는 것을 담당한다.<br>\r\n");
      out.write("		웹 페이지를 자동차에 비유하자면, HTML은 자동차의 뼈대, CSS는 자동차의 외관, JavaScript는 자동차의 동력이라고 볼 수 있다.\r\n");
      out.write("		</p><br>\r\n");
      out.write("	</li>\r\n");
      out.write("\r\n");
      out.write("	</ul>\r\n");
      out.write("	\r\n");
      out.write("	   <h3 class=\"h3_tit\">역사</h3>\r\n");
      out.write("   <ul class=\"list_style01\">\r\n");
      out.write("	<li><span class=\"bold\"> 개발자 브랜든 아이크, Ecma International</span>\r\n");
      out.write("		<p>\r\n");
      out.write("		첫 탄생은 1995년 넷스케이프에서 근무하던 브랜든 아이크가 10일만에 설계한 것으로부터 시작한다.<br> \r\n");
      out.write("		처음에는 Mocha라는 이름이었지만 4달 만에 LiveScript라는 이름으로 개명하고 다시 3달 후에는 <br>\r\n");
      out.write("		JavaScript라는 이름이 되어 오늘날까지 이어지고 있다. <br>\r\n");
      out.write("		'Java와 구문이 유사해서 이름을 JavaScript로 명명했다'는 표면상의 이유를 대지만 <br>\r\n");
      out.write("		그 속은 Java의 유명세를 타서 묻어가려고 의도적으로 그렇게 작명한 것이다. 물론 무단으로 도용한 것은 아니고, <br>\r\n");
      out.write("		썬 마이크로시스템즈(지금은 오라클에 인수됨)에게 상표권 사용 허락을 받았다. <br>\r\n");
      out.write("		# 오라클이 인수하면서 상표권도 오라클로 넘어갔는데, 소송으로 악명높은 오라클이 JavaScript는 딱히 손대지 않고 있다.<br>\r\n");
      out.write("		 애초에 허락을 맡은 것이기도 하고 JavaScript가 워낙 널리 쓰이다보니 이제는 서로 각자의 유명세에 보탬이 되는 상부상조 관계이기 때문.\r\n");
      out.write("		</p><br>\r\n");
      out.write("	</li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	<h3 class=\"h3_tit\">역사</h3>\r\n");
      out.write("   <ul class=\"list_style01\">\r\n");
      out.write("   <li><span class=\"bold\"><a href=\"https://www.nextree.co.kr/p7323/\"> JavaScript는 클래스라는 개념이 없습니다. 그래서 기존의 객체를 복사하여(cloning)<br> \r\n");
      out.write("	새로운 객체를 생성하는 프로토타입 기반의 언어입니다. 프로토타입 기반 언어는 객체 원형인 프로토타입을 이용하여 새로운 객체를 만들어냅니다.<br>\r\n");
      out.write("	이렇게 생성된 객체 역시 또 다른 객체의 원형이 될 수 있습니다. 프로토타입은 객체를 확장하고 객체 지향적인 프로그래밍을 할 수 있게 해줍니다.[</a></span>\r\n");
      out.write("		<p>\r\n");
      out.write("		부모 자식의 구분도 없으며, 메인 메소드 같은 것도 없고, 클래스-인스턴스 관계도 없으며, 모든 함수가 클래스도 될 수 있으며 인스턴스도 될 수 있다.<br> \r\n");
      out.write("		그렇기 때문에 모든 함수가 따로 놀기에 따라서 객체 지향처럼 \"서로 맞물리는\" 것을 기대할 수도 없다.(그런 이유로 클로저 개념이 있다.) <br>\r\n");
      out.write("		이 특성을 잘 이해해야 한다. 오히려 순서대로 읽는 절차 지향/객체 지향 언어보다는 모든 요소가 각자 따로 움직이는 <br>\r\n");
      out.write("		스타크래프트 맵 에디터 스크립트에 더 가까운 개념으로 이해해야 한다. 로드는 순서대로지만 실행은 동시 실행이다. <br>\r\n");
      out.write("		그러니까 main()같은건 없고 필요할때 실행되고 사라지는 스크립트들의 집합이라고 보면 된다. <br>\r\n");
      out.write("		오히려 웹 페이지 자체가 main()이라고 봐야 할 지경.\r\n");
      out.write("		</p><br><br><br>\r\n");
      out.write("		<p>\r\n");
      out.write("		JavaScript는 C에서 영향을 받은 C-Family 언어로 기본적인 문법이 유사 중괄호로 <br>\r\n");
      out.write("		구분하는 블럭, 세미콜론으로 줄이 끝남을 알리는 것, 변수 쓰는 법, 연산자 사용법 등 기초적인 문법이 C 문법과 크게 다르지 않다. <br>\r\n");
      out.write("		호이스팅 같은 것도 C언어의 잔재이다. 무엇보다 다른언어 쓰다온 사람들을 힘들게 하는건 클래스와 메소드가 외관으로 구분이 안된다라는 점이다.\r\n");
      out.write("		</p>\r\n");
      out.write("		<br><br><br>\r\n");
      out.write("		<p>\r\n");
      out.write("		JavaScript에서도 함수형 언어의 불편함과 호이스팅 등 여러 문제를 무마하기 위해서 클래스 개념의 도입과 <br>\r\n");
      out.write("		변수 선언을 let, const 로 하는 등 다른 언어 쓰는 사람들의 적응을 돕도록 흉내는 내 주는 척하는게 다행.<br> \r\n");
      out.write("		물론 일반적인 객체 지향 프로그래밍 개발자에게는 이것마저 이해를 못 하고 Syntatic Sugar에 불과한 JavaScript의 클래스를 불만족스러워한다.\r\n");
      out.write("		</p>\r\n");
      out.write("		\r\n");
      out.write("	</li>\r\n");
      out.write("   </ul>\r\n");
      out.write("	\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("     </div>\r\n");
      out.write("    <footer id=\"footer\" class=\"footer\">\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title> footer </title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"footer_n\">\r\n");
      out.write("        <div class=\"fnb_bg\">\r\n");
      out.write("                    <div class=\"fnb_group\">\r\n");
      out.write("                        <ul class=\"fg_list\">\r\n");
      out.write("                            <li class=\"fst\"><a href=\"\">이용안내</a></li>                \r\n");
      out.write("                            <li><a href=\"\"><span class=\"c_blue\">개인정보처리방침</span></a></li>\r\n");
      out.write("                            <li><a href=\"\">저작권정책</a></li>                  \r\n");
      out.write("                            <li><a href=\"\">누리집개선의견</a></li>\r\n");
      out.write("                            <li class=\"last\"><a href=\"\">찾아오시는길</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div id=\"siteListBox\">\r\n");
      out.write("                            <div id=\"siteList01\" class=\"siteList\">\r\n");
      out.write("                                <a href=\"http://kostat.go.kr/regional/gi/index.action\" onclick=\"kostatServiceDis('kostatagency','open');return false;\">소속기관</a>\r\n");
      out.write("                                <div class=\"moreSiteHidden\" id=\"kostatagency\">\r\n");
      out.write("                                    <ul class=\"sitetype01 bulType01\">\r\n");
      out.write("                                        <li><a href=\"\" target=\"_blank\" title=\"새 창으로 이동\">통계교육원</a></li>\r\n");
      out.write("                                        <li><a href=\"\" target=\"_blank\" title=\"새 창으로 이동\">통계개발원</a></li>\r\n");
      out.write("                                        <li> <a href=\"\"  target=\"_blank\" title=\"새 창으로 이동\">경인지방통계청</a> </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <p>소속기관<a href=\"index.html\" onclick=\"kostatServiceDis('kostatagency','close');return false;\">닫기</a></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div id=\"siteList02\" class=\"siteList\">\r\n");
      out.write("                                <a href=\"\" onclick=\"kostatServiceDis('kostatinfo','open');return false;\">통계정보</a>\r\n");
      out.write("                                <div class=\"moreSiteHidden\" id=\"kostatinfo\">\r\n");
      out.write("                                    <div class=\"siteType02\">\r\n");
      out.write("                                        <dl class=\"site_g\">\r\n");
      out.write("                                            <dt>통계정보</dt>\r\n");
      out.write("                                            <dd>\r\n");
      out.write("                                                <ul class=\"bulType01\">\r\n");
      out.write("                                                    <li><a href=\"\" target=\"_blank\"> 국가통계포털(KOSIS)</a></li>\r\n");
      out.write("                                                    <li><a href=\"\" target=\"_blank\">통계지리정보서비스(SGIS)</a></li>\r\n");
      out.write("                                                    <li><a href=\"\" target=\"_blank\">국가지표체계</a> </li>\r\n");
      out.write("                                                    <li><a href=\"\" target=\"_blank\">한눈에알아보는나라지표(e-나라지표)</a> </li>              \r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </dd>\r\n");
      out.write("                                        </dl>\r\n");
      out.write("                                        <dl class=\"site_g\">\r\n");
      out.write("                                            <dt>통계정책</dt>\r\n");
      out.write("                                            <dd>\r\n");
      out.write("                                                <ul class=\"bulType01\">\r\n");
      out.write("                                                    <li> <a href=\"\" target=\"_blank\" title=\"새 창으로 이동\" onclick=\"dummyAndPop2('http://narastat.kr/pms/index.do','/dummyURL?bmode=jongBo10');return false;\">통계정책관리시스템</a> </li>\r\n");
      out.write("                                                    <li> <a href=\"\" target=\"_blank\" title=\"새 창으로 이동\" onclick=\"dummyAndPop3('kostat.go.kr/policy/ssm/index.action','/dummyURL?bmode=jongBo11');return false;\">국가통계대행</a> </li>\r\n");
      out.write("                                                    <li><a href=\"\" target=\"_blank\" title=\"새 창으로 이동\" onclick=\"dummyAndPop2('http://kosis.kr/publication/publicationThema.do','/dummyURL?bmode=jongBo12');return false;\">온라인간행물</a></li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </dd>\r\n");
      out.write("                                        </dl>\r\n");
      out.write("                                        <dl class=\"site_g\">\r\n");
      out.write("                                            <dt>통계조사</dt>\r\n");
      out.write("                                            <dd>\r\n");
      out.write("                                                <ul class=\"bulType01\">\r\n");
      out.write("                                                    <li><a href=\"\"  target=\"_blank\">인구주택총조사</a> </li>\r\n");
      out.write("                                                    <li><a href=\"\" target=\"_blank\">농림어업총조사</a> </li>\r\n");
      out.write("                                                    <li><a href=\"\" target=\"_blank\">경제총조사 </a> </li>                                                                             \r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </dd>\r\n");
      out.write("                                        </dl>\r\n");
      out.write("                                        <dl class=\"site_g\">\r\n");
      out.write("                                            <dt>관련누리집</dt>\r\n");
      out.write("                                            <dd>\r\n");
      out.write("                                                <ul class=\"bulType01\">\r\n");
      out.write("                                                    <li> <a href=\"\" target=\"_blank\">소비자물가지수</a> </li>\r\n");
      out.write("                                                    <li> <a href=\"\"  target=\"_blank\">소득</a> </li>\r\n");
      out.write("                                                    <li> <a href=\"\" target=\"_blank\">100대 지표</a> </li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </dd>\r\n");
      out.write("                                        </dl>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p>통계정보 누리집<a href=\"index.html\" onclick=\"kostatServiceDis('kostatinfo','close');return false;\">닫기</a></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"add_group\">\r\n");
      out.write("                    <address>[1004] 일산동구 고양대로 956(식사동, 어딘가) 팩스 000-111-1004 / <strong>\r\n");
      out.write("                    <span class=\"call\">통계청콜센터 02-1004-1004</span> / <span class=\"call\">국번없이 110</span>\r\n");
      out.write("        </strong></address>\r\n");
      out.write("                    <p class=\"copy\">ⓒ Statistics Korea. All rights reserved since 2022.</p>\r\n");
      out.write("                    <h2 class=\"Hidden\">소셜미디어</h2>\r\n");
      out.write("                    <ul class=\"sns_list\">\r\n");
      out.write("                        <li class=\"icon_y\"><a href=\"http://kostat.go.kr/\" target=\"_blank\" onclick=\"dummyAndPop2('https://www.youtube.com/');return false;\"><span class=\"txt_sm\">유튜브</span></a></li>\r\n");
      out.write("                        <li class=\"icon_f\"><a href=\"http://kostat.go.kr/\" target=\"_blank\" onclick=\"dummyAndPop2('http://www.facebook.com/');return false;\"><span class=\"txt_sm\">페이스북</span></a></li>\r\n");
      out.write("                        <li class=\"icon_t\"><a href=\"http://kostat.go.kr/\" target=\"_blank\" onclick=\"dummyAndPop2('https://twitter.com/');return false;\"><span class=\"txt_sm\">트위터</span></a></li>\r\n");
      out.write("                        <li class=\"icon_b\"><a href=\"http://kostat.go.kr/\" target=\"_blank\" onclick=\"dummyAndPop2('https://blog.naver.com/');return false;\"><span class=\"txt_sm\">블로그</span></a></li>\r\n");
      out.write("                        <li class=\"icon_k\"><a href=\"http://kostat.go.kr/\"  target=\"_blank\" onclick=\"dummyAndPop2('https://www.instagram.com/');return false;\"><span class=\"txt_sm\">인스타그램</span></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- 소셜비디어 E -->\r\n");
      out.write("                    <p class=\"f_img02\"><a href=\"http://kostat.go.kr/file_total/WAQC_210910_kostat.pdf\" target=\"_blank\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/img_main/ico_wa.jpg\" alt=\"과학기술정보통신부 WEB ACCESSIBILITY 마크(웹 접근성 품질인증 마크)\" /></a></p>\r\n");
      out.write("                    <p class=\"f_img01\"><a href=\"http://www.kogl.or.kr/index.do\" target=\"_blank\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/img_main/kogl.gif\" alt=\"OPEN 공공누리:공공저작물 새창으로 열기\" /></a></p>\r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("    // 푸터에 소속기관 셀렉터창\r\n");
      out.write("function kostatServiceDis(id,evnt){                                                                                                                                 \r\n");
      out.write("	var clazz = document.getElementById(id).className;                                                                                                                \r\n");
      out.write("	if(evnt == \"open\"){                                                                                                                                               \r\n");
      out.write("  	if(clazz == \"moreSite\"){\r\n");
      out.write("  		document.getElementById(id).className = \"moreSiteHidden\";                                                                                                 \r\n");
      out.write("  	}else{                                                                                                                                                          \r\n");
      out.write("  		document.getElementById(id).className = \"moreSite\";                                                                                                        \r\n");
      out.write("  	}	                                                                                                                                                              \r\n");
      out.write("	}else{                                                                                                                                                            \r\n");
      out.write("		document.getElementById(id).className = \"moreSiteHidden\";                                                                                                   \r\n");
      out.write("	}                                                                                                                                                                 \r\n");
      out.write("}\r\n");
      out.write("function quickServiceDis(id,evnt){\r\n");
      out.write("	var clazz = document.getElementById(id);\r\n");
      out.write("	var clazzMain = document.getElementById(id+\"_main\");\r\n");
      out.write("	if(evnt == \"open\"){\r\n");
      out.write("  		clazz.className = \"\";\r\n");
      out.write("  		clazzMain.className = \"Dis_none\";\r\n");
      out.write("	}else{\r\n");
      out.write("  		clazz.className = \"Dis_none\";\r\n");
      out.write("  		clazzMain.className = \"\";\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/common.js\" ></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-3.3.1.min.js\" ></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/menuNew.js\" ></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/rollingIndexBanner.js\" ></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/mainBodo.js\" ></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/new_main.js\" ></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/board/boardList4.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path1");
      // /WEB-INF/views/board/boardList4.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/boardList4.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/board/../inc/header.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("path1");
      // /WEB-INF/views/board/../inc/header.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/../inc/header.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/board/../inc/header.jsp(35,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty sid}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	                    <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/loginForm.do\" >로그인</a></li>\r\n");
          out.write("	                    <li class=\"eng\"><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/joinForm.do\">회원가입</a></li>\r\n");
          out.write("	                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/board/../inc/header.jsp(40,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sid=='admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	                    <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/list.do\" >회원목록</a></li>\r\n");
          out.write("	                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/board/../inc/header.jsp(44,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty sid}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	                    <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/read.do\" >마이페이지</a></li>\r\n");
          out.write("	                    <li class=\"eng\"><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/logout.do\">로그아웃</a></li>\r\n");
          out.write("	                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/views/board/../inc/footer.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("path1");
      // /WEB-INF/views/board/../inc/footer.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/../inc/footer.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }
}
