/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-07-12 09:11:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/D:/ksm/jsp4/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web06/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/inc/main.jsp", Long.valueOf(1657609192607L));
    _jspx_dependants.put("/WEB-INF/views/inc/header.jsp", Long.valueOf(1657616903305L));
    _jspx_dependants.put("/WEB-INF/views/inc/footer.jsp", Long.valueOf(1657617044010L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1655111722494L));
    _jspx_dependants.put("jar:file:/D:/ksm/jsp4/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web06/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("   \n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-latest.js\"></script>\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-1.11.0.min.js\"></script>\n");
      out.write("\n");
      out.write("	<title>Home</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"wrap\">\n");
      out.write("	<header id=\"header\" class=\"header\">\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"icon\" href=\"../../img_total/n_favicon_n_16.png\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"https://kostat.go.kr/img_total/favicon_kostat.ico\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/NotoSansKR-Hestia_Main.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style_content.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style_layout_master.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/master.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style_board.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/reset_new_n.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/code.css\" media=\"all\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<title> header </title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("        <div id=\"skip\">\r\n");
      out.write("            <p class=\"Hidden\">반복영역 건너뛰기</p>\r\n");
      out.write("           <ul class=\"accessibility\">\r\n");
      out.write("               	<li><a href=\"#mcont_s\">본문바로가기</a></li>\r\n");
      out.write("               	<li><a href=\"#gnb_s1\">주요메뉴바로가기</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("       </div>\r\n");
      out.write("        <div id=\"header_n\">             \r\n");
      out.write("            <div id=\"tnb_layout\">\r\n");
      out.write("            <div class=\"t_nav\">\r\n");
      out.write("                <h1 class=\"t_logo\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/logo.png\" alt=\"통계청\" /></a></h1>\r\n");
      out.write("                <ul class=\"sitelink_r\">\r\n");
      out.write("                \r\n");
      out.write("	                ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	                \r\n");
      out.write("	                ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	                \r\n");
      out.write("	                ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	                \r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>  \r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"mnb_layout\">\r\n");
      out.write("            \r\n");
      out.write("            <!-- 통계청 검색기능 -->\r\n");
      out.write("            <h2 class=\"Hidden\">통합검색</h2>\r\n");
      out.write("    <div class=\"search_m_open\">\r\n");
      out.write("       <a href=\"http://kostat.go.kr/wnsearch/search.jsp\" target=\"_blank\">검색 열기</a>\r\n");
      out.write("      </div>\r\n");
      out.write("            <div id=\"search\"> \r\n");
      out.write("            <script> \r\n");
      out.write("    function quickSearch(query){\r\n");
      out.write("        var frm = document.sForm;\r\n");
      out.write("        frm.action = \"https://kostat.go.kr/wnsearch/search.jsp\";\r\n");
      out.write("        frm.query.value = query;\r\n");
      out.write("        frm.submit();\r\n");
      out.write("    }\r\n");
      out.write("        function goSearch(){\r\n");
      out.write("            var frm = document.sForm;\r\n");
      out.write("            var name = document.getElementById(\"query\").value;\r\n");
      out.write("    if(name  == null || name == \"\"){\r\n");
      out.write("    alert(\"검색어를 입력하세요.\");\r\n");
      out.write("    document.getElementById(\"query\").focus();\r\n");
      out.write("    return false;\r\n");
      out.write("    }\r\n");
      out.write("                frm.action = \"https://kostat.go.kr/wnsearch/search.jsp\";\r\n");
      out.write("                frm.submit();\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        function handlepress(){	\r\n");
      out.write("            if(event.keyCode == 13){	\r\n");
      out.write("                goSearch();	\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        function selectWord(word){\r\n");
      out.write("            var frm = document.sForm;\r\n");
      out.write("            frm.query.value=word;\r\n");
      out.write("            frm.submit();\r\n");
      out.write("        }\r\n");
      out.write("        function kostat() {\r\n");
      out.write("            alert(\"현재 검색이 원활히 되지 않고 있습니다. 이용에 불편을 드려 죄송합니다. 빠른 시일내에 복구하도록 하겠습니다.\");\r\n");
      out.write("        }\r\n");
      out.write("    </script><noscript>스크립트 기능이 중지되어 있어, 게시판 화면을 정상적으로 표시할 수 없습니다. </noscript>\r\n");
      out.write("    <form name=\"sForm\" method=\"post\" action=\"https://kostat.go.kr/wnsearch/search.jsp\" onsubmit=\"return goSearch();\">\r\n");
      out.write("          <fieldset>\r\n");
      out.write("          <legend class=\"Hidden\">통합검색</legend>\r\n");
      out.write("        <label for=\"collection\" class=\"Hidden\">검색분류</label>\r\n");
      out.write("        <select name=\"collection\" id=\"collection\"  title=\"검색분류\">\r\n");
      out.write("    <option value=\"ALL\" selected=\"selected\">통합검색</option>\r\n");
      out.write("            <option value=\"web_bodo\">통계청 누리집</option>\r\n");
      out.write("            <option value=\"statDB\">국가통계포털(KOSIS) 통계표</option>\r\n");
      out.write("            <option value=\"enara\" >한눈에알아보는나라지표(e-나라지표)</option>\r\n");
      out.write("            <option value=\"class\" >통계분류</option>\r\n");
      out.write("            <option value=\"online\" >온라인간행물</option>\r\n");
      out.write("            <option value=\"metaDB\" >통계설명자료</option>\r\n");
      out.write("            <option value=\"statTerms\">통계용어</option>\r\n");
      out.write("            <option value=\"employee\">직원검색</option>\r\n");
      out.write("            <option value=\"hire\">채용정보</option>\r\n");
      out.write("        </select>\r\n");
      out.write("            <label for=\"query\"  class=\"Hidden\" >통합검색창</label>\r\n");
      out.write("            <input name=\"query\" type=\"text\" id=\"query\" class=\"searchInput\" value=\"\" title=\"검색어\" style=\"ime-mode:active;\" />\r\n");
      out.write("            <label for=\"btn_ts_search\"  class=\"Hidden\">검색</label>\r\n");
      out.write("    <input type=\"submit\" id=\"btn_ts_search\"  value=\"검색\"/>\r\n");
      out.write("          </fieldset>\r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"relation_link\">\r\n");
      out.write("                <li class=\"fst\"><a href=\"http://kostat.go.kr/\"  target=\"_blank\" title=\"새창\" class=\"c_point\"><strong>민원</strong></a></li>\r\n");
      out.write("                <li><a href=\"http://kostat.go.kr/\" target=\"_blank\" title=\"새창\">통계이해</a></li>\r\n");
      out.write("                <li><a href=\"http://kostat.go.kr/\"  target=\"_blank\" title=\"새창\">채용</a></li>\r\n");
      out.write("                <li class=\"last\"><a href=\"http://kostat.go.kr/\"  target=\"_blank\" title=\"새창\">통계조사</a></li>\r\n");
      out.write("             </ul>   \r\n");
      out.write("              </div>\r\n");
      out.write("              </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("	</header>\n");
      out.write("\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html;charset=UTF-8\" />\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/theeluwin/NotoSansKR-Hestia@master/stylesheets/NotoSansKR-Hestia.css\" integrity=\"sha384-zGzb8nSrN9lm5PPcfztVC5DjjTs5sVStV85IH8x51fM9yIwmI+Uvh3RZDJlrpPWQ\" crossorigin=\"anonymous\">\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("<meta name=\"description\" content=\"국가통계포털, 마이크로데이터, 통계지리정보, 정보공개, 새소식, 정책정보, 통계청소개\" />\r\n");
      out.write("<meta name=\"google-site-verification\" content=\"CdVvMTdPwr71iinMXgKSkU9CzBWJA2iBun2uMWJ2oqc\"/>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" /> \r\n");
      out.write("<title>통계청</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body >\r\n");
      out.write("\r\n");
      out.write("<div id=\"gnb_layout\">\r\n");
      out.write("<div class=\"g_nav\">\r\n");
      out.write("	<h2 class=\"Hidden\">주메뉴</h2>\r\n");
      out.write("	<ul id=\"mn_list\" class=\"lnb_list\">\r\n");
      out.write("		<li class=\"mn_type01\"><a href=\"\" id=\"gnb_s1\">프로그램언어종류</a></li>\r\n");
      out.write("		<li class=\"mn_type02\"><a href=\"\">소프트웨어종류</a></li>\r\n");
      out.write("		<li class=\"mn_type02\"><a href=\"\">운영체제종류</a></li>\r\n");
      out.write("\r\n");
      out.write("    <li class=\"mn_type03\" id=\"gnb1\" ><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list.do\" >정보공개</a>\r\n");
      out.write("	  	<ul class=\"Hidden\">\r\n");
      out.write("		    <li id=\"gnb1_9\"><a href=\"\">정보공개제도</a></li>    \r\n");
      out.write("		    <li id=\"gnb1_1\"><a href=\"\">정보목록</a></li>    \r\n");
      out.write("		    <li id=\"gnb1_0\"><a href=\"\">사전정보공표</a></li>    \r\n");
      out.write("		    <li id=\"gnb1_4\"><a href=\"\">행정자료실</a></li>    \r\n");
      out.write("		    <li id=\"gnb1_6\"><a href=\"\">정책실명제</a></li>    \r\n");
      out.write("		    <li id=\"gnb1_7\"><a href=\"\">공공데이터개방</a></li>    \r\n");
      out.write("		    <li id=\"gnb1_8\"><a href=\"\" target=\"_blank\"  title=\"새창\">협동조합경영공시</a></li>    \r\n");
      out.write("    	</ul>\r\n");
      out.write("	</li>\r\n");
      out.write("    <li class=\"mn_type03\" id=\"gnb2\" ><a href=\"\" >새소식</a>\r\n");
      out.write("	  	<ul class=\"Hidden\">\r\n");
      out.write("		    <li id=\"gnb2_1\"><a href=\"\">보도자료</a></li>    \r\n");
      out.write("		    <li id=\"gnb2_2\"><a href=\"\" target=\"_blank\"  title=\"새창\">보도영상</a></li>    \r\n");
      out.write("			<li id=\"gnb2_3\"><a href=\"\">정책뉴스</a></li>\r\n");
      out.write("		    <li id=\"gnb2_4\"><a href=\"\">언론보도설명</a></li>    \r\n");
      out.write("			<li id=\"gnb2_5\"><a href=\"\">보도계획</a></li>\r\n");
      out.write("		    <li id=\"gnb2_6\"><a href=\"\">공지사항</a></li>    \r\n");
      out.write("		    <li id=\"gnb2_7\"><a href=\"\" target=\"_blank\"  title=\"새창\">홍보영상</a></li>    \r\n");
      out.write("		    <li id=\"gnb2_8\"><a href=\"\" target=\"_blank\"  title=\"새창\">소식편지</a></li>    \r\n");
      out.write("    	</ul>\r\n");
      out.write("	</li>\r\n");
      out.write("    <li class=\"mn_type03\" id=\"gnb3\" ><a href=\"\" >정책정보</a>\r\n");
      out.write("	  	<ul class=\"Hidden\">\r\n");
      out.write("		    <li id=\"gnb3_1\"><a href=\"\">주요업무계획</a></li>    \r\n");
      out.write("		    <li id=\"gnb3_2\"><a href=\"\">국가승인통계현황</a></li>    \r\n");
      out.write("		    <li id=\"gnb3_3\"><a href=\"\">법령자료</a></li>    \r\n");
      out.write("		    <li id=\"gnb3_4\"><a href=\"\">국가통계발전포럼</a></li>    \r\n");
      out.write("			<li id=\"gnb3_5\"><a href=\"\">정책자료</a></li>\r\n");
      out.write("		    <li id=\"gnb3_6\"><a href=\"\">국가통계위원회</a></li>    \r\n");
      out.write("		    <li id=\"gnb3_7\"><a href=\"\">통계기반정책평가제도</a></li>    \r\n");
      out.write("		    <li id=\"gnb3_b\"><a href=\"\">실험적통계제도</a></li>    \r\n");
      out.write("		    <li id=\"gnb3_8\"><a href=\"\">통계품질관리</a></li>     \r\n");
      out.write("    	</ul>\r\n");
      out.write("	</li>\r\n");
      out.write("    <li class=\"mn_type03\" id=\"gnb4\" ><a href=\"\" >통계청소개</a>\r\n");
      out.write("	  	<ul class=\"Hidden\">\r\n");
      out.write("			<li id=\"gnb4_1\"><a href=\"\">미션및비전</a></li>\r\n");
      out.write("			<li id=\"gnb4_2\"><a href=\"\">국가통계기본원칙</a></li>\r\n");
      out.write("			<li id=\"gnb4_3\"><a href=\"\">청/차장</a></li>    \r\n");
      out.write("			<li id=\"gnb4_4\"><a href=\"\">일반현황</a></li>    \r\n");
      out.write("			<li id=\"gnb4_5\"><a href=\"\">조직안내</a></li>    \r\n");
      out.write("			<li id=\"gnb4_6\"><a href=\"\">시설물 안내</a></li>    \r\n");
      out.write("      	</ul>\r\n");
      out.write("	</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("    <div id=\"mcont\">\r\n");
      out.write("       <div class=\"info_link_bg\">\r\n");
      out.write("<div class=\"info_link\">\r\n");
      out.write("  <h2 class=\"Hidden\">통계정보 사이트 목록</h2>\r\n");
      out.write("  <div class=\"list_box icon1\">\r\n");
      out.write("    <h3><a href=\"\" target=\"_blank\" >뉴스기반통계검색</a></h3>\r\n");
      out.write("    <h3 class=\"info_l_tit\"><a href=\"\" target=\"_blank\" >국가통계포털(KOSIS)</a></h3>\r\n");
      out.write("    <ul>\r\n");
      out.write("      <li><a href=\"\" target=\"_blank\">국내통계</a></li>\r\n");
      out.write("      <li><a href=\"\" target=\"_blank\">국제통계</a></li>\r\n");
      out.write("      <li><a href=\"\" target=\"_blank\">북한통계</a></li>\r\n");
      out.write("      <li><a href=\"\" target=\"_blank\">쉽게보는 통계</a></li>\r\n");
      out.write("      <li><a href=\"\"  target=\"_blank\">지방지표</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <h3 class=\"info_l_tit\"><a href=\"\" target=\"_blank\">통계설명자료</a></h3>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"list_box icon2\">\r\n");
      out.write("    <h3><a href=\"\"  target=\"_blank\">마이크로데이터(MDIS)</a></h3>\r\n");
      out.write("    <ul>\r\n");
      out.write("      <li><a href=\"\" target=\"_blank\">이용안내</a></li>\r\n");
      out.write("      <li><a href=\"\" target=\"_blank\">제공항목 목록</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <h3 class=\"info_l_tit\"><a href=\"\" target=\"_blank\">통계데이터센터(SDC)</a></h3>    \r\n");
      out.write("      <ul>\r\n");
      out.write("  		  <li><a href=\"\" target=\"_blank\">이용안내</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("<h3 class=\"info_l_tit\"><a href=\"\"  target=\"_blank\">빅데이터활용<br/>(Nowcast)</a></h3>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"list_box icon3\">\r\n");
      out.write("    <h3><a href=\"\"  target=\"_blank\" >통계지리정보(SGIS)</a></h3>   \r\n");
      out.write("    <h3 class=\"info_l_tit\"><a href=\"\"  target=\"_blank\">국가지표체계</a></h3>\r\n");
      out.write("    <h3 class=\"info_l_tit\"><a href=\"\" target=\"_blank\" class=\"tLine\">한눈에알아보는나라지표<br />(e-나라지표)</a></h3>\r\n");
      out.write("	<h3 class=\"info_l_tit icon4\"><a href=\"\"  target=\"_blank\">통계분류포털</a></h3>\r\n");
      out.write("	<ul>\r\n");
      out.write("        <li><a href=\"\"  target=\"_blank\">한국표준산업분류</a></li>\r\n");
      out.write("        <li><a href=\"\"  target=\"_blank\">한국표준직업분류</a></li>\r\n");
      out.write("        <li><a href=\"\"  target=\"_blank\">한국표준질병ㆍ사인분류</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"list_box line_bg\">\r\n");
      out.write("    <div class=\"section1 icon4 covid_kr_1\">\r\n");
      out.write("		<a href=\"\" target=\"_blank\" ><span class=\"red\">코로나19</span> <span>(COVID-19)</span></a>\r\n");
      out.write("	</div>\r\n");
      out.write("<div class=\"section2 icon5\">\r\n");
      out.write("<ul>\r\n");
      out.write("        <li><a href=\"\" target=\"_blank\">통계청통계 전체보기</a></li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <a class=\"l_tit\" target=\"_blank\" href=\"\">진행 중인 조사</a>\r\n");
      out.write("         <ul>\r\n");
      out.write("            <li><a href=\"\" target=\"_blank\" title=\"새 창으로 이동\">가계동향조사</a></li>\r\n");
      out.write("<li><a href=\"\"  target=\"_blank\" title=\"새 창으로 이동\">경제활동인구조사</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>    \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("        <!-- 100대 지표 S -->\r\n");
      out.write("<div class=\"second_area\">        \r\n");
      out.write("    <div class=\"indicator\">\r\n");
      out.write("      	<h2><a href=\"http://kostat.go.kr/\" onclick=\"statPopupOpen(); return false;\" target=\"_blank\">100대지표 더보기+</a></h2>\r\n");
      out.write("            <ul>\r\n");
      out.write("				<li  id=\"jipyo1\"><a href=\"\" onclick=\"statPopupOpen('15','1179'); return false;\" title=\"새창\"><span class=\"bold\">전산업생산지수(전월비)</span>('22.05) <span class=\"b_point\">0.8</span>%</a></li>\r\n");
      out.write("				<li  id=\"jipyo2\"><a href=\"\" onclick=\"statPopupOpen('16','1165'); return false;\" title=\"새창\"><span class=\"bold\">소매판매액지수(전월대비)</span>('22.05) <span class=\"b_point\">-0.1</span>%</a></li>\r\n");
      out.write("				<li  id=\"jipyo3\"><a href=\"\" onclick=\"statPopupOpen('18','1187'); return false;\" title=\"새창\"><span class=\"bold\">국민총소득(GNI,명목)</span>('21) <span class=\"b_point\">2,094,721.3</span>십억원</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"third_area\">\r\n");
      out.write("	<div class=\"group_L\">\r\n");
      out.write("		<ul class=\"news_b pd_t\">\r\n");
      out.write("			<li>\r\n");
      out.write("			<h2 class=\"tit_s1n_on\" id=\"bdh2\"><a href=\"\" onclick=\"showHeadLineFunc('news','bdh2','hmh2','newheadline','haemyungline','efh2'); return false;\"><span class=\"r_line\">보도자료</span></a></h2>\r\n");
      out.write("				<div id=\"newheadline\">\r\n");
      out.write("					<div class=\"list_breif\">    \r\n");
      out.write("						<dl id=\"pn01\" style=\"display: block\">\r\n");
      out.write("							<dt><a href=\"\" target=\"_self\" title=\"title\">title</a></dt>\r\n");
      out.write("							<dd><a href=\"\" target=\"_self\" title=\" title\"><span class=\"text\"> text</span></a><span class=\"data2\">ragdate</span></dd>								\r\n");
      out.write("						</dl>\r\n");
      out.write("						<dl id=\"pn02\" style=\"display:none\">\r\n");
      out.write("				  			<dt><a href=\"\" target=\"_self\" title=\"title\">title</a></dt>\r\n");
      out.write("							<dd><a href=\"\" target=\"_self\" title=\" title \"><span class=\"text\"> text</span></a>\r\n");
      out.write("							<span class=\"data2\">regdate</span></dd>								\r\n");
      out.write("						</dl>\r\n");
      out.write("						<dl id=\"pn03\" style=\"display:none\">\r\n");
      out.write("				  			<dt><a href=\"\" target=\"_self\" title=\"title\">title</a></dt>\r\n");
      out.write("							<dd><a href=\"\" target=\"_self\" title=\"title\"><span class=\"text\">text</span></a><span class=\"data2\">ragedate</span></dd>								\r\n");
      out.write("						</dl>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"on\" id=\"pn0_1\"><a href='' id=\"pnl1\" onfocus=\"contentHover('news_play_img');moveNewsTv('news',1);\" onblur=\"contentOut('news_play_img');\" onmouseover=\"this.onfocus();\" onmouseout=\"this.onblur();\" title=\"title\"><span class=\"bul\">title</span></a><span class=\"date\">regdate</span></li>\r\n");
      out.write("							<li id=\"pn0_2\"><a href='' id=\"pnl2\"  onfocus=\"contentHover('news_play_img');moveNewsTv('news',2);\" onblur=\"contentOut('news_play_img');\" onmouseover=\"this.onfocus();\" onmouseout=\"this.onblur();\" title=\"title\"><span class=\"bul\">title</span></a><span class=\"date\">regdate</span></li>\r\n");
      out.write("							<li id=\"pn0_3\"><a href='' id=\"pnl3\"  onfocus=\"contentHover('news_play_img');moveNewsTv('news',3);\" onblur=\"contentOut('news_play_img');\" onmouseover=\"this.onfocus();\" onmouseout=\"this.onblur();\" title=\"title\"><span class=\"bul\">title</span></a><span class=\"date\">regdate</span></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<p class=\"more2\"><span class=\"Hidden\">보도자료</span></a></p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li>\r\n");
      out.write("			<h2 class=\"tit_s2n\" id=\"hmh2\"><a onclick=\"showHeadLineFunc('haemyung','hmh2','bdh2','haemyungline','newheadline','efh2'); return false;\"><span class=\"r_line\">언론보도설명</span></a></h2>\r\n");
      out.write("				<div id=\"haemyungline\"  class=\"Dis_none\">\r\n");
      out.write("					<div class=\"list_breif\">    \r\n");
      out.write("						<dl id=\"ph01\" style=\"display: block\">\r\n");
      out.write("						 	<dt><a href=\"\" target=\"_self\" title=\"title\">title</a></dt>\r\n");
      out.write("							<dd><a href=\"\" target=\"_self\" title=\"title\"><span class=\"text\"> text</span></a><span class=\"data2\">regdate</span></dd>								\r\n");
      out.write("						</dl>\r\n");
      out.write("						<dl id=\"ph02\" style=\"display:none\">\r\n");
      out.write("  							<dt><a href=\"\" target=\"_self\" title=\" tile\">title</a></dt>\r\n");
      out.write("							<dd><a href=\"\" target=\"_self\" title=\"title\"><span class=\"text\">text</span></a><span class=\"data2\">regdate</span></dd>								\r\n");
      out.write("						</dl>\r\n");
      out.write("						<dl id=\"ph03\" style=\"display:none\">\r\n");
      out.write("				  			<dt><a href=\"\" target=\"_self\" title=\"title\">title</a></dt>\r\n");
      out.write("							<dd><a href=\"\" target=\"_self\" title=\"title\"><span class=\"text\">text</span></a><span class=\"data2\">regdate</span></dd>								\r\n");
      out.write("						</dl>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"on\" id=\"ph0_1\"><a href='' id=\"phl1\" onfocus=\"focusHover('haemyung_stop');moveHaemyung('haemyung',1);\" onblur=\"focusOut('haemyung_play');\" onmouseover=\"this.onfocus();\" onmouseout=\"this.onblur();\" title=\"title\"><span class=\"bul\">title</span></a><span class=\"date\">regdate</span></li>\r\n");
      out.write("							<li id=\"ph0_2\"><a href='' id=\"phl2\"  onfocus=\"focusHover('haemyung_stop');moveHaemyung('haemyung',2);\" onblur=\"focusOut('haemyung_play');\" onmouseover=\"this.onfocus();\" onmouseout=\"this.onblur();\" title=\"title\"><span class=\"bul\">title</span></a><span class=\"date\">regdate</span></li>\r\n");
      out.write("							<li id=\"ph0_3\"><a href='' id=\"phl3\"  onfocus=\"focusHover('haemyung_stop');moveHaemyung('haemyung',3);\" onblur=\"focusOut('haemyung_play');\" onmouseover=\"this.onfocus();\" onmouseout=\"this.onblur();\" title=\"title\"><span class=\"bul\">title</span></a><span class=\"date\">regdate</span></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<p class=\"more2\"><span class=\"Hidden\">언론보도설명</span></p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</li>        \r\n");
      out.write("		<div class=\"\">\r\n");
      out.write("			<div class=\"career_b\">\r\n");
      out.write("				<h2 class=\"l_tit\">채용정보</h2>                    \r\n");
      out.write("				<div class=\"line_t\">    \r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a target=\"_blank\" href=\"\"><span class=\"local\">[지역]</span>[지역]title</a><span class=\"date\">regdate</span></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<p class=\"more\"><a href=\"\" target=\"_blank\">채용정보</span>더보기+</a></p>      \r\n");
      out.write("				</div>              \r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"notice_b\">\r\n");
      out.write("				<h2 class=\"l_tit\">공지사항</h2>\r\n");
      out.write("				<div class=\"line_t\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("				<p class=\"more\"><a href=\"\"  onclick=\"dummyAndPop1('/portal/korea/kor_nw/6/1/index.board','/dummyURL?bmode=gongGi');return false;\"><span class=\"Hidden\">공지사항</span>더보기+</a></p>   \r\n");
      out.write("				</div>\r\n");
      out.write("			</div>           \r\n");
      out.write("		</div>            \r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"group_R\">\r\n");
      out.write("		<div class=\"popup_zone\">\r\n");
      out.write("	    	<h2 class=\"r_tit\">알림판</h2>\r\n");
      out.write("		<p class=\"count\" id=\"bannerCount\"><span class=\"p_num\">-</span></p>    	\r\n");
      out.write("	    <div class=\"pz_btn\">\r\n");
      out.write("			<a href=\"\" class=\"prev\" onclick=\"RP_num.previous();return false;\"><span class=\"Hidden\">알림판 이전</span></a>\r\n");
      out.write("			<a href=\"\" class=\"stop\" id=\"btnPause\"  onclick=\"pause('btnPause','btnPlay');return false;\" style=\"display:block;\"><span class=\"Hidden\">알림판 정지</span></a>\r\n");
      out.write("			<a href=\"\" class=\"play\" id=\"btnPlay\"  onclick=\"pause('btnPlay','btnPause');return false;\" style=\"display:none;\" ><span class=\"Hidden\">알림판 시작</span></a>\r\n");
      out.write("			<a href=\"\" class=\"next\" onclick=\"RP_num.next();return false;\" ><span class=\"Hidden\">알림판 다음</span></a>\r\n");
      out.write("		</div>\r\n");
      out.write("<ul class=\"pz_list\" id=\"IntroList\">\r\n");
      out.write("<script src=\"js/alrimpan.js\"/>\r\n");
      out.write("<script>\r\n");
      out.write("var main_delay_time = 5000;\r\n");
      out.write("var RP_num = new RollingBanner();\r\n");
      out.write("var timer_num;\r\n");
      out.write("var flag = false;\r\n");
      out.write("		RP_num.addBanner(\"img/alrimpan_banner/banner_0628_01.png\", \"통계연구 제27권 제2호 발간 자세히보기\",);	\r\n");
      out.write("		RP_num.addBanner(\"img/alrimpan_banner/banner_0627_03.png\", \"KOSTAT Statistics Plus vol.18 2022. 6.  「KOSTAT 통계플러스」2022년 여름호 발간   주요내용 이슈분석, 통계프리즘, 통계포커스  발행부서: 통계개발원 연구기획실 바로가기(새창열기)\");	\r\n");
      out.write("		RP_num.addBanner(\"img/alrimpan_banner/banner_0623_02.png\", \"우리 가족이 하루에 사용하는 물의 양은 얼마나 될까요? 데이터(숫자 등)로 한번 생각해보고, 의견을 남겨주세요! 2022. 6. 22.(수) ~ 7. 12.(화) 국민 누구나 가능\");	\r\n");
      out.write("		RP_num.addBanner(\"img/alrimpan_banner/banner_0609_01.png\", \"제20대대통령직인수위원회백서 겸손하게 국민의 뜻을 받들겠습니다. \");	\r\n");
      out.write("		RP_num.addBanner(\"img/alrimpan_banner/banner_0602_01.png\", \"제9회 2022 국가승인통계 활용 디지털 콘텐츠 공모전 통계로 바라본 대한민국의 (?) 공모기간 : 2022.06.02. ~ 2022. 07. 31. 공모전 페이지바로가기(새창열기)\");	\r\n");
      out.write("		RP_num.addBanner(\"img/alrimpan_banner/banner_0527_01.png\", \"2022년 통계데이터 분석활용대회 2022.5.25.~7.27. 데이터야! 나랑 깐부할래? 바로가기(새창열기)\");	\r\n");
      out.write("		RP_num.addBanner(\"img/alrimpan_banner/board211005.jpg\", \"통계청 SK telecom 통신 모바일 인구이동량 통계 실험적 통계 1호로 서비스\");	\r\n");
      out.write("	RP_num.write();\r\n");
      out.write("function pause(obj,subobj) {\r\n");
      out.write("    	var alrimpan= document.getElementById(obj);\r\n");
      out.write("    	var alrimpan_sub= document.getElementById(subobj);\r\n");
      out.write("if(obj == \"btnPause\"){\r\n");
      out.write("	alrimpan.style.display = \"none\";\r\n");
      out.write("	alrimpan_sub.style.display = \"block\";\r\n");
      out.write("clearInterval(timer_num);\r\n");
      out.write("}else{\r\n");
      out.write("	alrimpan_sub.style.display = \"block\";\r\n");
      out.write("	alrimpan.style.display = \"none\";\r\n");
      out.write("timer_num= setInterval(\"RP_num.next()\",main_delay_time); \r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("//페이지 로딩시 자동재생이 아닌 일시정지시킬경우 주석처리함.\r\n");
      out.write("	timer_num = setInterval(\"RP_num.next()\",main_delay_time); \r\n");
      out.write("	//]]>\r\n");
      out.write("</script>\r\n");
      out.write("</ul>\r\n");
      out.write("<noscript>스크립트 기능이 중지되어 있어, 알림판 더보기를 클릭 해 확인 해 주세요.</noscript>\r\n");
      out.write("<p class=\"more\"><a href=\"\"><span class=\"Hidden\">알림판</span>더보기+</a></p>\r\n");
      out.write("</div>\r\n");
      out.write("            <div class=\"popular_service\">\r\n");
      out.write("            	<h2 class=\"r_tit\">자주찾는 서비스</h2>\r\n");
      out.write("            	  <div id=\"div_ps_list_main\" class=\"ps_box\">\r\n");
      out.write("                <div class=\"ps_list\">\r\n");
      out.write("                	<ul>\r\n");
      out.write("                    	<li class=\"ps_icon_01\"><a href=\"\"  target=\"_blank\">민원신청</a></li>\r\n");
      out.write("                    	<li class=\"ps_icon_02\"><a href=\"\">보도계획</a></li>\r\n");
      out.write("                    	<li class=\"ps_icon_03\"><a href=\"\">적극행정</a></li>\r\n");
      out.write("                    </ul>                    \r\n");
      out.write("                </div>\r\n");
      out.write("            	<p class=\"more\"><a href=\"http://kostat.go.kr/\" onclick=\"quickServiceDis('div_ps_list','open');return false;\"><span class=\"Hidden\">자주찾는 서비스</span>펼쳐보기+</a></p>     \r\n");
      out.write("            	 </div>\r\n");
      out.write("               <!-- 펼쳐보기 눌렀을때 -->\r\n");
      out.write("               <div id=\"div_ps_list\" class=\"Dis_none ps_box\">\r\n");
      out.write("               <div class=\"ps_list_on\">\r\n");
      out.write("                	<ul>\r\n");
      out.write("                    	<li class=\"ps_icon_01\"><a href=\"\"  target=\"_blank\">민원신청</a></li>\r\n");
      out.write("                    	<li class=\"ps_icon_02\"><a href=\"\">보도계획</a></li>\r\n");
      out.write("                    	<li class=\"ps_icon_03\"><a href=\"\">적극행정</a></li>\r\n");
      out.write("                    	<li class=\"ps_icon_04\"><a href=\"\">정보공개</a></li>\r\n");
      out.write("                    	<li class=\"ps_icon_05\"><a href=\"\">조직도</a></li>\r\n");
      out.write("                    	<li class=\"ps_icon_06\"><a href=\"\" target=\"_blank\">소식편지</a></li>                	\r\n");
      out.write("                    </ul>                    \r\n");
      out.write("                </div>                    \r\n");
      out.write("            	<p class=\"more\"><a href=\"http://kostat.go.kr/\" onclick=\"quickServiceDis('div_ps_list','close');return false;\"><span class=\"Hidden\">자주찾는 서비스</span>닫기 -</a></p>      \r\n");
      out.write("                </div>   \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"banner_zone\">\r\n");
      out.write("            	<h2 class=\"r_tit\">정책광고</h2>\r\n");
      out.write("                <div class=\"bz_list\">\r\n");
      out.write("                	<ul id=\"bannerList\" class=\"listb\">\r\n");
      out.write("                    	<li>&nbsp;</li>\r\n");
      out.write("                    </ul>                    \r\n");
      out.write("                </div>\r\n");
      out.write("              <script src=\"js/rollingIndexBanner.js\"></script>\r\n");
      out.write("		<script>\r\n");
      out.write("			var MB = new RollingBanner();\r\n");
      out.write("			MB.setDisplayCount(2);\r\n");
      out.write("			MB.addBanner(\"./img/img_main/banner_0328_01.png\", \"통계청기업통계등록부정비 2022.3.18.~12/14.\",);\r\n");
      out.write("			MB.addBanner(\"./img/img_main/banner210625.png\", \"국가상징 알아보기\",);\r\n");
      out.write("			MB.write();\r\n");
      out.write("		</script>\r\n");
      out.write("<noscript>스크립트 기능이 중지되어 있어, 정책광고 더보기를 클릭 해 확인 해 주세요.</noscript> \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write(" <!-- 마지막 div는 헤더에서 내려오는것임 -->\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("	// 100대 지표 더보기+ 누르면 이동되도록\r\n");
      out.write("function statPopupOpen(listId, num) {\r\n");
      out.write("	var url=\"\";\r\n");
      out.write("	if (listId == undefined || num == undefined || listId == \"\" || num == \"\" || listId == null || num == null) {\r\n");
      out.write("		url = \"https://kosis.kr/visual/nsportalStats/index.do?menuId=all\";\r\n");
      out.write("         $.getJSON(location.protocol + '//' + location.host +'/dummyURL?bmode=100jipyo');\r\n");
      out.write("	} else {\r\n");
      out.write("		url = \"https://kosis.kr/visual/nsportalStats/index.do?menuId=\" + listId + \"&NUM=\" + num;\r\n");
      out.write("	}\r\n");
      out.write("	var win = window.open(url, \"KOSIS100대지표\", 'location=no,directories=no,resizable=yes,status=no,toolbar=no,scrollbars=yes,width=1080,height=700, left=0, top=0');\r\n");
      out.write("	win.focus();\r\n");
      out.write("}\r\n");
      out.write("// 푸터에 소속기관 셀렉터창\r\n");
      out.write("function kostatServiceDis(id,evnt){                                                                                                                                 \r\n");
      out.write("	var clazz = document.getElementById(id).className;                                                                                                                \r\n");
      out.write("	if(evnt == \"open\"){                                                                                                                                               \r\n");
      out.write("  	if(clazz == \"moreSite\"){\r\n");
      out.write("  		document.getElementById(id).className = \"moreSiteHidden\";                                                                                                 \r\n");
      out.write("  	}else{                                                                                                                                                          \r\n");
      out.write("  		document.getElementById(id).className = \"moreSite\";                                                                                                        \r\n");
      out.write("  	}	                                                                                                                                                              \r\n");
      out.write("	}else{                                                                                                                                                            \r\n");
      out.write("		document.getElementById(id).className = \"moreSiteHidden\";                                                                                                   \r\n");
      out.write("	}                                                                                                                                                                 \r\n");
      out.write("}\r\n");
      out.write("function quickServiceDis(id,evnt){\r\n");
      out.write("	var clazz = document.getElementById(id);\r\n");
      out.write("	var clazzMain = document.getElementById(id+\"_main\");\r\n");
      out.write("	if(evnt == \"open\"){\r\n");
      out.write("  		clazz.className = \"\";\r\n");
      out.write("  		clazzMain.className = \"Dis_none\";\r\n");
      out.write("	}else{\r\n");
      out.write("  		clazz.className = \"Dis_none\";\r\n");
      out.write("  		clazzMain.className = \"\";\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getStrNo(str){\r\n");
      out.write("   if(str<10){\r\n");
      out.write("     return \"0\"+str;\r\n");
      out.write("   }else{\r\n");
      out.write("     return str;\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("var now = new Date();\r\n");
      out.write("var aa = now.getYear()+''+getStrNo((now.getMonth()+1))+''+getStrNo(now.getDate())+''+getStrNo(now.getHours())+''+getStrNo(now.getMinutes());\r\n");
      out.write("var url = \"http://kostat.go.kr/portal/common/s019801/popup1411.html\";\r\n");
      out.write("</script>\r\n");
      out.write("<script> \r\n");
      out.write("	window.onload = function(){\r\n");
      out.write("$(\"#pn0_1\").append($('#pn01').wrap(\"<dt>\").parent().html());\r\n");
      out.write("$('#pn01').eq(0).parent().remove();\r\n");
      out.write("$(\"#pn0_2\").append($('#pn02').wrap(\"<dt>\").parent().html());\r\n");
      out.write("$('#pn02').eq(0).parent().remove();\r\n");
      out.write("$(\"#pn0_3\").append($('#pn03').wrap(\"<dt>\").parent().html());\r\n");
      out.write("$('#pn03').eq(0).parent().remove();\r\n");
      out.write("$(\"#pn0_4\").append($('#pn04').wrap(\"<dt>\").parent().html());\r\n");
      out.write("$('#pn04').eq(0).parent().remove();\r\n");
      out.write("$(\"#pn0_5\").append($('#pn05').wrap(\"<dt>\").parent().html());\r\n");
      out.write("$('#pn05').eq(0).parent().remove();\r\n");
      out.write("$(\"#ph0_1\").append($('#ph01').wrap(\"<dt>\").parent().html());\r\n");
      out.write("$('#ph01').eq(0).parent().remove();\r\n");
      out.write("$(\"#ph0_2\").append($('#ph02').wrap(\"<dt>\").parent().html());\r\n");
      out.write("$('#ph02').eq(0).parent().remove();\r\n");
      out.write("$(\"#ph0_3\").append($('#ph03').wrap(\"<dt>\").parent().html());\r\n");
      out.write("$('#ph03').eq(0).parent().remove();\r\n");
      out.write("$(\"#ph0_4\").append($('#ph04').wrap(\"<dt>\").parent().html());\r\n");
      out.write("$('#ph04').eq(0).parent().remove();\r\n");
      out.write("$(\"#ph0_5\").append($('#ph05').wrap(\"<dt>\").parent().html());\r\n");
      out.write("$('#ph05').eq(0).parent().remove();\r\n");
      out.write("	};\r\n");
      out.write(" //]]>\r\n");
      out.write("</script> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("	<footer id=\"footer\" class=\"footer\">\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title> footer </title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"footer_n\">\r\n");
      out.write("        <div class=\"fnb_bg\">\r\n");
      out.write("                    <div class=\"fnb_group\">\r\n");
      out.write("                        <ul class=\"fg_list\">\r\n");
      out.write("                            <li class=\"fst\"><a href=\"\">이용안내</a></li>                \r\n");
      out.write("                            <li><a href=\"\"><span class=\"c_blue\">개인정보처리방침</span></a></li>\r\n");
      out.write("                            <li><a href=\"\">저작권정책</a></li>                  \r\n");
      out.write("                            <li><a href=\"\">누리집개선의견</a></li>\r\n");
      out.write("                            <li class=\"last\"><a href=\"\">찾아오시는길</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div id=\"siteListBox\">\r\n");
      out.write("                            <div id=\"siteList01\" class=\"siteList\">\r\n");
      out.write("                                <a href=\"http://kostat.go.kr/regional/gi/index.action\" onclick=\"kostatServiceDis('kostatagency','open');return false;\">소속기관</a>\r\n");
      out.write("                                <div class=\"moreSiteHidden\" id=\"kostatagency\">\r\n");
      out.write("                                    <ul class=\"sitetype01 bulType01\">\r\n");
      out.write("                                        <li><a href=\"\" target=\"_blank\" title=\"새 창으로 이동\">통계교육원</a></li>\r\n");
      out.write("                                        <li><a href=\"\" target=\"_blank\" title=\"새 창으로 이동\">통계개발원</a></li>\r\n");
      out.write("                                        <li> <a href=\"\"  target=\"_blank\" title=\"새 창으로 이동\">경인지방통계청</a> </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <p>소속기관<a href=\"index.html\" onclick=\"kostatServiceDis('kostatagency','close');return false;\">닫기</a></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div id=\"siteList02\" class=\"siteList\">\r\n");
      out.write("                                <a href=\"\" onclick=\"kostatServiceDis('kostatinfo','open');return false;\">통계정보</a>\r\n");
      out.write("                                <div class=\"moreSiteHidden\" id=\"kostatinfo\">\r\n");
      out.write("                                    <div class=\"siteType02\">\r\n");
      out.write("                                        <dl class=\"site_g\">\r\n");
      out.write("                                            <dt>통계정보</dt>\r\n");
      out.write("                                            <dd>\r\n");
      out.write("                                                <ul class=\"bulType01\">\r\n");
      out.write("                                                    <li><a href=\"\" target=\"_blank\"> 국가통계포털(KOSIS)</a></li>\r\n");
      out.write("                                                    <li><a href=\"\" target=\"_blank\">통계지리정보서비스(SGIS)</a></li>\r\n");
      out.write("                                                    <li><a href=\"\" target=\"_blank\">국가지표체계</a> </li>\r\n");
      out.write("                                                    <li><a href=\"\" target=\"_blank\">한눈에알아보는나라지표(e-나라지표)</a> </li>              \r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </dd>\r\n");
      out.write("                                        </dl>\r\n");
      out.write("                                        <dl class=\"site_g\">\r\n");
      out.write("                                            <dt>통계정책</dt>\r\n");
      out.write("                                            <dd>\r\n");
      out.write("                                                <ul class=\"bulType01\">\r\n");
      out.write("                                                    <li> <a href=\"\" target=\"_blank\" title=\"새 창으로 이동\" onclick=\"dummyAndPop2('http://narastat.kr/pms/index.do','/dummyURL?bmode=jongBo10');return false;\">통계정책관리시스템</a> </li>\r\n");
      out.write("                                                    <li> <a href=\"\" target=\"_blank\" title=\"새 창으로 이동\" onclick=\"dummyAndPop3('kostat.go.kr/policy/ssm/index.action','/dummyURL?bmode=jongBo11');return false;\">국가통계대행</a> </li>\r\n");
      out.write("                                                    <li><a href=\"\" target=\"_blank\" title=\"새 창으로 이동\" onclick=\"dummyAndPop2('http://kosis.kr/publication/publicationThema.do','/dummyURL?bmode=jongBo12');return false;\">온라인간행물</a></li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </dd>\r\n");
      out.write("                                        </dl>\r\n");
      out.write("                                        <dl class=\"site_g\">\r\n");
      out.write("                                            <dt>통계조사</dt>\r\n");
      out.write("                                            <dd>\r\n");
      out.write("                                                <ul class=\"bulType01\">\r\n");
      out.write("                                                    <li><a href=\"\"  target=\"_blank\">인구주택총조사</a> </li>\r\n");
      out.write("                                                    <li><a href=\"\" target=\"_blank\">농림어업총조사</a> </li>\r\n");
      out.write("                                                    <li><a href=\"\" target=\"_blank\">경제총조사 </a> </li>                                                                             \r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </dd>\r\n");
      out.write("                                        </dl>\r\n");
      out.write("                                        <dl class=\"site_g\">\r\n");
      out.write("                                            <dt>관련누리집</dt>\r\n");
      out.write("                                            <dd>\r\n");
      out.write("                                                <ul class=\"bulType01\">\r\n");
      out.write("                                                    <li> <a href=\"\" target=\"_blank\">소비자물가지수</a> </li>\r\n");
      out.write("                                                    <li> <a href=\"\"  target=\"_blank\">소득</a> </li>\r\n");
      out.write("                                                    <li> <a href=\"\" target=\"_blank\">100대 지표</a> </li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </dd>\r\n");
      out.write("                                        </dl>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p>통계정보 누리집<a href=\"index.html\" onclick=\"kostatServiceDis('kostatinfo','close');return false;\">닫기</a></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"add_group\">\r\n");
      out.write("                    <address>[1004] 일산동구 고양대로 956(식사동, 어딘가) 팩스 000-111-1004 / <strong>\r\n");
      out.write("                    <span class=\"call\">통계청콜센터 02-1004-1004</span> / <span class=\"call\">국번없이 110</span>\r\n");
      out.write("        </strong></address>\r\n");
      out.write("                    <p class=\"copy\">ⓒ Statistics Korea. All rights reserved since 2022.</p>\r\n");
      out.write("                    <h2 class=\"Hidden\">소셜미디어</h2>\r\n");
      out.write("                    <ul class=\"sns_list\">\r\n");
      out.write("                        <li class=\"icon_y\"><a href=\"http://kostat.go.kr/\" target=\"_blank\" onclick=\"dummyAndPop2('https://www.youtube.com/');return false;\"><span class=\"txt_sm\">유튜브</span></a></li>\r\n");
      out.write("                        <li class=\"icon_f\"><a href=\"http://kostat.go.kr/\" target=\"_blank\" onclick=\"dummyAndPop2('http://www.facebook.com/');return false;\"><span class=\"txt_sm\">페이스북</span></a></li>\r\n");
      out.write("                        <li class=\"icon_t\"><a href=\"http://kostat.go.kr/\" target=\"_blank\" onclick=\"dummyAndPop2('https://twitter.com/');return false;\"><span class=\"txt_sm\">트위터</span></a></li>\r\n");
      out.write("                        <li class=\"icon_b\"><a href=\"http://kostat.go.kr/\" target=\"_blank\" onclick=\"dummyAndPop2('https://blog.naver.com/');return false;\"><span class=\"txt_sm\">블로그</span></a></li>\r\n");
      out.write("                        <li class=\"icon_k\"><a href=\"http://kostat.go.kr/\"  target=\"_blank\" onclick=\"dummyAndPop2('https://www.instagram.com/');return false;\"><span class=\"txt_sm\">인스타그램</span></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- 소셜비디어 E -->\r\n");
      out.write("                    <p class=\"f_img02\"><a href=\"http://kostat.go.kr/file_total/WAQC_210910_kostat.pdf\" target=\"_blank\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/img_main/ico_wa.jpg\" alt=\"과학기술정보통신부 WEB ACCESSIBILITY 마크(웹 접근성 품질인증 마크)\" /></a></p>\r\n");
      out.write("                    <p class=\"f_img01\"><a href=\"http://www.kogl.or.kr/index.do\" target=\"_blank\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/img_main/kogl.gif\" alt=\"OPEN 공공누리:공공저작물 새창으로 열기\" /></a></p>\r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("    // 푸터에 소속기관 셀렉터창\r\n");
      out.write("function kostatServiceDis(id,evnt){                                                                                                                                 \r\n");
      out.write("	var clazz = document.getElementById(id).className;                                                                                                                \r\n");
      out.write("	if(evnt == \"open\"){                                                                                                                                               \r\n");
      out.write("  	if(clazz == \"moreSite\"){\r\n");
      out.write("  		document.getElementById(id).className = \"moreSiteHidden\";                                                                                                 \r\n");
      out.write("  	}else{                                                                                                                                                          \r\n");
      out.write("  		document.getElementById(id).className = \"moreSite\";                                                                                                        \r\n");
      out.write("  	}	                                                                                                                                                              \r\n");
      out.write("	}else{                                                                                                                                                            \r\n");
      out.write("		document.getElementById(id).className = \"moreSiteHidden\";                                                                                                   \r\n");
      out.write("	}                                                                                                                                                                 \r\n");
      out.write("}\r\n");
      out.write("function quickServiceDis(id,evnt){\r\n");
      out.write("	var clazz = document.getElementById(id);\r\n");
      out.write("	var clazzMain = document.getElementById(id+\"_main\");\r\n");
      out.write("	if(evnt == \"open\"){\r\n");
      out.write("  		clazz.className = \"\";\r\n");
      out.write("  		clazzMain.className = \"Dis_none\";\r\n");
      out.write("	}else{\r\n");
      out.write("  		clazz.className = \"Dis_none\";\r\n");
      out.write("  		clazzMain.className = \"\";\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"../js/common.js\" ></script>\r\n");
      out.write("<script src=\"../js/jquery-3.3.1.min.js\" ></script>\r\n");
      out.write("<script src=\"../js/menuNew.js\" ></script>\r\n");
      out.write("<script src=\"../js/rollingIndexBanner.js\" ></script>\r\n");
      out.write("<script src=\"../js/mainBodo.js\" ></script>\r\n");
      out.write("<script src=\"../js/new_main.js\" ></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("	</footer>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/home.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path1");
      // /WEB-INF/views/home.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/home.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/inc/header.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("path1");
      // /WEB-INF/views/inc/header.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/inc/header.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/inc/header.jsp(35,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty sid}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	                    <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/loginForm.do\" >로그인</a></li>\r\n");
          out.write("	                    <li class=\"eng\"><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/joinForm.do\">회원가입</a></li>\r\n");
          out.write("	                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/inc/header.jsp(40,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sid=='admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	                    <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/list.do\" >회원목록</a></li>\r\n");
          out.write("	                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/inc/header.jsp(44,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty sid}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	                    <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/read.do\" >마이페이지</a></li>\r\n");
          out.write("	                    <li class=\"eng\"><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/logout.do\">로그아웃</a></li>\r\n");
          out.write("	                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/views/inc/main.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("path1");
      // /WEB-INF/views/inc/main.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/inc/main.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/inc/main.jsp(214,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/inc/main.jsp(214,5) '${noticeList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${noticeList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/inc/main.jsp(214,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("notice");
      // /WEB-INF/views/inc/main.jsp(214,5) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("					<li><a href=\"\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a><span class=\"date\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.regdate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f3_reused = false;
    try {
      _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f3.setParent(null);
      // /WEB-INF/views/inc/footer.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setVar("path1");
      // /WEB-INF/views/inc/footer.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/inc/footer.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
      if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      _jspx_th_c_005fset_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f3_reused);
    }
    return false;
  }
}
